/**
 * @framesquared/grid – RowBody feature
 *
 * Adds an expandable body row below each data row with
 * custom content generated by getAdditionalData.
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

export interface RowBodyConfig {
  getAdditionalData: (
    data: any,
    rowIndex: number,
    record: any,
  ) => { rowBody: string; rowBodyCls?: string };
}

export class RowBody {
  private grid: any = null;
  private getAdditionalData: RowBodyConfig['getAdditionalData'];

  constructor(config: RowBodyConfig) {
    this.getAdditionalData = config.getAdditionalData;
  }

  init(grid: any): void {
    this.grid = grid;
    this.addRowBodies();
  }

  private addRowBodies(): void {
    const view = this.grid?.getView?.();
    if (!view) return;
    const table = view.getTable?.();
    if (!table) return;
    const tbody = table.querySelector('tbody');
    if (!tbody) return;

    const store = this.grid.getStore();
    const records = store.getRange();
    const columns = this.grid.getColumns();
    const rows = Array.from(tbody.querySelectorAll('tr.x-grid-row')) as HTMLElement[];

    for (let i = 0; i < rows.length && i < records.length; i++) {
      const rec = records[i];
      const result = this.getAdditionalData(rec.data, i, rec);
      const bodyRow = document.createElement('tr');
      bodyRow.classList.add('x-grid-rowbody');
      if (result.rowBodyCls) bodyRow.classList.add(result.rowBodyCls);
      const td = document.createElement('td');
      td.colSpan = columns.length;
      td.innerHTML = result.rowBody;
      bodyRow.appendChild(td);
      rows[i].after(bodyRow);
    }
  }
}
